p=int(input("Enter prime number p :"))
q=int(input("Enter prime number q : "))
a=int(input("Enter assumed key for Alice : "))
b=int(input("Enter assumed key for Bob : "))
A=pow(q,a,p)
B=pow(q,b,p)
print("Exchange of keys takes place")
AKey=pow(B, a, p)
BKey=pow(A, b, p)
print(f'The secret key for Alice is : {AKey}')
print(f'The secret key for Bob is : {BKey}')
